### ISSUE TITLE
Wireframe Design Library

### ISSUE THREAD

**Issue by kathrynmcelroy** [IBM-Watson/design-library#123]
- [x] Principles
- [x] Guidelines
- [x] UI Patterns

**Comment by kathrynmcelroy** [comment]
I completed the initial wireframe to test the IA. @bobbinrobyn is currently working on an updated wireframe to use for visual design.

**Comment by bobbinrobyn** [comment]
I've been working on wireframing all day, and I can sync up with @britanyponvelle tomorrow to show off where I'm at. I'll do my best to be done by EOD tomorrow.

**Comment by bobbinrobyn** [comment]
Things to be thinking about:
Will we have an image at the top of each main section (Principles, Guidelines, UI Patterns)? Or will it just start with a heading?

**Comment by Snugug** [comment]
I'm going to caution against an image, that's going to increase our page load time substantially without much boost to our usability. Maybe @ryanbrownhill can come up with some interesting animations that are small in size and responsive.

**Comment by joshkimmell** [comment]
I think Robyn, Kathryn, Britany, Ryan, Jessica can come together and get to an amazing solution that considers usability and performance. Maybe an image is a good solution, maybe not. Please take Sam's caution to heart and move forward.

**Comment by bobbinrobyn** [comment]
Something else to think about:
Are we going to have an ever-present search/filter?

**Comment by bobbinrobyn** [comment]
I hosted my Axure wireframes/prototype here. Still lots of work to go, but at least it's a good start for the Principles and Guidelines sections. http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/principles.html

**Comment by ryanbrownhill** [comment]
Looks good @bobbinrobyn ! I think we can create some kind of svg animation at the top instead of an image. Some initial ideas: Watson logo animating on, simple animation of an icon that represents principles.

At minimum I think doing a simple header animation for the intro would work (like IBM Design is working on) :
![header-animation](https://cloud.githubusercontent.com/assets/9538395/6863027/5cfc6dd4-d418-11e4-85a3-f33533bfe3b9.gif)

@Snugug if we are going to be doing more svg animations we might want to consider something like snap.svg because a gif fallback or svg enhancement wouldn't be ideal in this case.

**Comment by Snugug** [comment]
Robyn: no persistent search for the first iteration

Ryan: 73Kb for a JavaScript library gives me goosebumps; that's a lot of weight before we have anything to show for it and is likely to have serious performance implications especially on low powered devices (phones and tablets, for instance)

We can have a single color fallback instead of an animated gif fallback, or to think about it in the terms of progressive enhancement, we can have each header have a colored background representing it and, if svg animations are available, enhance with an svg animation. We don't need things to look the same everywhere, they won't. We need things to be usable everywhere at the best available enhancement they can muster.

**Comment by britanyponvelle** [comment]
I will run with this today, and upload my progress in #74 and #71

**Comment by bobbinrobyn** [comment]
I anticipate being able to close this issue today.

**Comment by bobbinrobyn** [comment]
I've wireframed with the content types that we have, so I think we're good to close this issue. Any additional wireframing that needs to be done should be minor. http://pages.design.ibm.com/rlhammon/watson-color-palettes/master/axure%20wireframes/#p=principles

**Comment by Snugug** [comment]
What's the progress on this? Is this done?

**Comment by ryanbrownhill** [comment]
:+1: on my end

**Comment by britanyponvelle** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:
