### ISSUE TITLE
Grid Recommendations

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#125]
Write recommendations for determining a fluid grid system

**Comment by britanyponvelle** [comment]
@joshkimmell can you assign this to @poofichu?

**Comment by poofichu** [comment]
Going to reference this:
http://pointnorth.io/#grids

**Comment by poofichu** [comment]
##Grids

Grids are utilized to keep order on a page.  They provide order and structure to a document as well as enforce proportion and constraint on a design.  Ideally, a grid is specific to the content and design of a site, and it should be an extension of both.

Do not choose a grid system first - your content will help dictate and decide what grid system you decide to work with.

//Instead of using generic grid systems (Twitter Bootstrap, Zurb Foundation), content-out layouts are recommended.  Grid Frameworks (Singularity, Susy) are excellent, because they provide the flexibility needed to create complex and robust content-out responsive grids.

###Visual Example

Responsive Grid Context - Display
http://snugug.github.io/responsive-grids/#/responsive-grids-display

###Resources

1 - Grids Section of IBM Design Language (http://www.ibm.com/design/language/framework/visual/layout.shtml)

**Comment by poofichu** [comment]
** Discussion scheduled for tomorrow to talk about responsive grids and relation to how visual designer should keep them in mind -- @Snugug has some GREAT resources as to how to incorporate them into the front-end, but we need to translate this information for visual designers.

@ryanbrownhill @bobbinrobyn @britanyponvelle @britanyponvelle Please comment with any ideas/suggestions to the information provided in the previous comment!!

**Comment by Snugug** [comment]
So instead of stealing from me, I recommend pilfering from http://alistapart.com/article/content-out-layout.

In regards to what's written, I'd drop the grid systems bit. I'd talk about [layouts](https://github.com/IBM-Watson/design-library/issues/93#issuecomment-83206754) and mention that unless otherwise specified our layouts are built using [Singularity](https://github.com/at-import/singularity). Reinforce content out layouts and choosing the points at which to change your grid based on your content and design and where those things break, not at where device sizes are.

**Comment by poofichu** [comment]
## Grids
> Grids establish order and provide fluid structure.

* IBM Design Language http://www.ibm.com/design/language/framework/visual/layout.shtml *

## Web Grids vs. Print Grids

Web grids and print grids are not the same.  Print grids deal with a fixed display and content size with limited user distraction.  Web grids have many and varied display sizes with varied content lengths, sizes, and types.  Web grids also come with numerous reading modes and a wide potential range of additional user distractions.

### Visual Example

http://bradfrost.com/wp-content/uploads/2012/03/this-is-not-web.png
http://bradfrost.com/wp-content/uploads/2012/03/this-is-the-web.png
http://bradfrost.com/wp-content/uploads/2012/03/this-will-bethe-web.png

## Responsive Grids

> A ratio-based, modular approach to grids allows us to navigate a medium where we cannot know the container size, nor what type of content will flow into that container.

* Nathan Ford
http://alistapart.com/article/content-out-layout *

Ratios are used to help set the tone for compositions - your content sets the tone and therefore your layout will mirror that.  The chosen ratio will be the basis around what layout decisions are made.

Layout systems can be built based around the content, and ratios can be used to keep the compositions harmonious.

### Visual Example

Responsive Grid Context - Display
http://snugug.github.io/responsive-grids/#/responsive-grids-display

### Resources

1 - Grids Section of IBM Design Language (http://www.ibm.com/design/language/framework/visual/layout.shtml)

**Comment by poofichu** [comment]
@britanyponvelle @Snugug take a look please!

**Comment by Snugug** [comment]
We should start getting these in to PRs so we can comment line by line. I've got some updates I'd like to make, I'll do it tomorrow

**Comment by poofichu** [comment]
Yes to pull requests!  We'll work it out tomorrow.

**Comment by britanyponvelle** [comment]
It looks great! Do you intend to link to the pages you listed here? For the first section I think it would be helpful to say why designing this way is beneficial to the user. Something like this? (my additions are in bold):

## Grids
> Grids establish order and provide fluid structure. **Using a grid to organize content will increase legibility and optimize visual experiences for users.**

Also, in the responsive grids section, is there some kind of tool we can link to to help designers determine the most appropriate ratio for their content? I know I would find that helpful :-)

**Comment by Snugug** [comment]
Okay, here's my thought on a rewrite. I also think Brad's *the web* images aren't right for this section; the images in Nathan's blog post are better, or we may need to make our own: https://github.com/IBM-Watson/design-library/wiki/Grids

**Comment by poofichu** [comment]
@Snugug I LIKE IT.  It does, in my opinion, need some sort of visual examples.  I would like to still include your [responsive grid context ](http://snugug.github.io/responsive-grids/#/responsive-grids-display) but maybe adjust it and show in some visual way that you can use %/em and create a ratio -- content controls your breakpoints, not devices.

**Comment by Snugug** [comment]
Yah, agreed it needs a visual example or two

**Comment by ryanbrownhill** [comment]
:+1: done via #167

**Comment by britanyponvelle** [comment]
:+1: done

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by Snugug** [comment]
This will close then once that gets merged in
