### ISSUE TITLE
Design for Principles Page

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#145]
Visual design for Principles> Design Principles page.

**Comment by bobbinrobyn** [comment]
**Introduce Cognitive**  
_Give first-time users a set of "cognitive training wheels" and continue to provide unobtrusive support as needed._  

- Clarify Watson’s capabilities with hierarchy, copy, and interactions to help set appropriate user expectations.  
- Educate the user throughout the experience without interrupting his or her workflow. Integrate additional explanation into the visual hierarchy as a secondary focus so that it doesn’t get in the way of more experienced users.
- Reinforce cognitive behaviors with intelligent defaults and positive feedback in order to gradually adjust the user’s habits.


**Inform Interactions**  
_Make it a smooth ride for a user by informing the user's interactions as they use Watson to discover valuable insights and perform desired tasks._  

- Present insights as quickly as possible, with an indication of accuracy or obscurity.
- Demonstrate Watson’s heavy lifting with visual metaphors and indications of the actions Watson takes. Increase transparency when it helps the user trust the accuracy of the insights Watson returns.
- Display Watson’s insights as the user needs them, so that interfaces aren’t cluttered or overwhelming. This technique, known as progressive disclosure, improves usability by displaying only the relevant information needed to complete a given task.


**Offer Control**  
_Let the user choose to take the "highways or byways" by offering control when a user wants it. Watson experiences should naturally adapt to amplify the user's abilities and expertise._  

- Denote a clear best path through the experience, while accommodating alternatives and seamless undos if the user wants to try something else.
- Support users with visual design and copy that indicate collaboration or a conversation. Demonstrate that users learn from Watson, and at the same time, Watson learns from them.
- Provide personalization options that are both manual (performed by the user) and automatic (performed by Watson). Gather user information and preferences to apply to the experience, as well as enabling a cycle of continuous feedback between Watson and the user.

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/design_principles.html

**Comment by bobbinrobyn** [comment]
Today @poofichu and I discussed some changes, including:
* reduce spacing between title of principle and the long description
* changing the styling of the long description (on the condition that I find other content that can adopt the same styling, so that it's not just a one-off custom styling for a single piece of content)
* increase spacing between sub-principle chunks (a chunk being image + copy)
* try a different layout with full-width images

**Comment by bobbinrobyn** [comment]
@poofichu and I are working on wrapping this up today! Once we have it nailed down, we can format the content from #116 in a markdown file and submit a pull request.

**Comment by poofichu** [comment]
Ready for review!!

**Comment by Snugug** [comment]
The descriptions under each principle title are currently built as headings presumably to get the desired visual hierarchy. My question is, semantically, should those things be headings? Are they actually headings for the content, and if so, why does the same content have two headings? Is it a sub-heading? If so (from [HTML5 Doctor](http://html5doctor.com/howto-subheadings/):

> h1–h6 elements must not be used to markup subheadings, subtitles, alternative titles and taglines unless intended to be the heading for a new section or subsection.

If it's not a heading and it's not a sub-heading, it shouldn't be visually larger than body copy. Strong or emphasized, sure, but not larger.

**Comment by bobbinrobyn** [comment]
@Snugug I'd say it's a sub-heading.

**Comment by Snugug** [comment]
If it's a sub heading it can't be marked up in heading tags, so y'all should talk about it

**Comment by bobbinrobyn** [comment]
Thoughts @poofichu? (Besides the thought that styling those sentences is so incredibly annoying? Haha, because I already hear you on that.)

**Comment by poofichu** [comment]
Going with a bold paragraph.

**Comment by britanyponvelle** [comment]
:+1:

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1: done

**Comment by bobbinrobyn** [comment]
Unfortunately, not done :disappointed:

I'm going to redo the files so that each principle lives on its own page, given the decision we made about IA in #93. Then we should be good to review & close this today.

**Comment by bobbinrobyn** [comment]
:+1: I changed my mind. Visual design (this issue) is definitely done. Content for principles (#116) will be done today.
