### ISSUE TITLE
Design for Grids Page

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#146]
Visual design for Guidelines> Grids page.

**Comment by poofichu** [comment]
![wdl-grids](https://cloud.githubusercontent.com/assets/6757613/6926195/42bf76ba-d7aa-11e4-9332-2cd274d8e6ca.png)

**Comment by poofichu** [comment]
![wdl-grids-grey](https://cloud.githubusercontent.com/assets/6757613/6926973/b0f06018-d7af-11e4-8c9a-9bba289383f0.png)

Took out the crayola grid examples.  Liking the grey much better.  @britanyponvelle @Snugug comments?

We're still working with Hayley on the content.  TBD.

**Comment by britanyponvelle** [comment]
"Crayola" LOL. They grey is nice because it's not so loud, although I do like the way the color helps to break up the blocks of text. Perhaps using values of one color would make it less "crayola"? The visual examples are great! Very informative.

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/grids.html

Grid page coded and up for review.  Visual examples redone to have darker accents.  Video created at the bottom with responsive grid example.  @channel any feedback?

**Comment by britanyponvelle** [comment]
This is looking great! Using the caption size text next to the body copy for this makes it kind of look like  a disclaimer rather than a quote. What do you think?

**Comment by Snugug** [comment]
Agreed with @britanyponvelle, not sure why the blockquotes have smaller fonts; our official blockquote pattern has it at 1em.

In general, I want to make sure that we are in fact using the standard styling from our pattern library for this as much as possible in order to avoid this being a one-off and not dogfooding our own work.

**Comment by joshkimmell** [comment]
I agree. IF we feel that the default styling isn't working, we should change the default styling in the pattern.

**Comment by bobbinrobyn** [comment]
Haha, that is an awesome Stephen Hay quote. A few thoughts: 

1. Can this sentence be reworded to make it a little clearer? Right now it says, "Instead, grids need to be fluid and flexible, extending out from our content out." But maybe it could say, "Instead, grids need to be fluid and flexible, beginning with the content and extending out from there."

2. This sentence should be split into two separate sentences: "Ratios can be used to help set the tone for compositions, choose one that makes sense for the type of content being displayed."

3. I wonder what it would look like to have the colors inverted on the images. As it is, it feels to me like the borders and gutters are getting more visual weight than the columns.

**Comment by poofichu** [comment]
@britanyponvelle Good catch on the blockquote.  It was leftover CSS from back when we had a the orange bar on the caption... Back to 1em.  Let's discuss width/padding too.

@bobbinrobyn I made the text changes you suggested.  Here's the examples with the colors "flipped":
I'm torn.  Thoughts @joshkimmell @Snugug @britanyponvelle ?

![image](https://cloud.githubusercontent.com/assets/6757613/7008260/76f919f8-dc56-11e4-8fa3-524d535b4204.png)

**Comment by joshkimmell** [comment]
I like this better. The lighter tones are easier to decipher.

**Comment by bobbinrobyn** [comment]
I'm not sure, I could see going with either option. If I had to choose, I think I would go with this lighter option, where the columns are the darker gray. But I think either the light or the dark could work well!

**Comment by britanyponvelle** [comment]
I think the last version is the strongest. The dark grey is reserved for content (which would be inside of the columns) versus putting heavy emphasis on padding space so I think it makes the most sense!

**Comment by kathrynmcelroy** [comment]
I prefer the lighter gray as the background. It puts the focus on the darker gray content, which makes up the grid.

**Comment by joshkimmell** [comment]
I think it's decided. Anyone want to argue for the dark borders?

**Comment by poofichu** [comment]
Thanks for the feedback guys!  Updating the assets....

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/grids.html

Assets updated to light grey background!

**Comment by joshkimmell** [comment]
Great! Could you also change the name to Watson Design Guide?

**Comment by ryanbrownhill** [comment]
![screen shot 2015-04-06 at 3 36 09 pm](https://cloud.githubusercontent.com/assets/9538395/7011904/b9391784-dc72-11e4-97ca-3bd820c2f659.png)
@poofichu  - Something is happening with the floating nav - IDK if this is a known problem

**Comment by poofichu** [comment]
@ryanbrownhill refresh your browser.  It's a buggy jQuery script thing.

**Comment by ryanbrownhill** [comment]
@poofichu --- Yes that fixes it.

**Comment by kathrynmcelroy** [comment]
For this round of feedback, I'm doing a bit of copy-editing for this section.
- We're using a lot of "our" in this write-up, and we don't do that elsewhere. We should probably tune down the "our"s and make it a little more general, in the edited text I've changed out a few of these for alternatives
- Edited the grammar a bit; there's still a bit of passive voice, but it's ok in context
I'll send this over to Jessica for the coded site

**Comment by kathrynmcelroy** [comment]
Updated text:

Grids enforce proportion and constraint upon our designs, providing order and structure to information. The best grid is specific to the displayed content and the design, as it is an extension of both. When used correctly, a grid will enhance, balance, and structure content, so users can read and view the information with ease.

Grids do not exist in a vacuum. They exist in relation to the content. We never start with a grid. We start with an idea which is then translated into a form, a structure.
Linda van Deursen

When working with grids on the web, there are additional items that must be considered: the many and varied display sizes with variable content lengths, sizes, and types; numerous reading modes; and a wide potential range of additional user distractions. As such, one grid for all contexts is not a realistic expectation. Instead, grids need to be fluid and flexible, beginning with the content and extending out from there.

A ratio-based, modular approach to grids allows us to navigate a medium where we cannot know the container size, nor what type of content will flow into that container.
Nathan Ford

Ratios can be used to help set the tone for compositions. Choose one that makes sense for the type of content being displayed. Orderly, highly structured content or designs, like image galleries, may benefit from symmetric grids where each column is the same size. More organic content or designs, like a mixture of text and images, may benefit from asymmetric grids where column sizes are based on a harmonic ratio scale like the golden ratio. This can be especially powerful when the ratio is shared with our typographic scales. Content or designs that are meant to be slightly chaotic may benefit from asymmetric grids where column sizes vary and are not directly tied to each other.


Responsive Grids
When designing for the ever evolving, unstable medium of the web, we must take care to ensure that the layouts work no matter the context. In order to do so, the grids need to be flexible and fluid, stretching and condensing to fill their space. At some points, though, the design or the content will no longer be displayed the way we would like. At this point we should change the grid to allow the content and design to be rearranged into a more optimal display.

Start with the small screen first, then expand until it looks like shit. TIME FOR A BREAKPOINT!
Stephen Hay

When designing responsive grids, the smallest size should be designed first, using as close to real content as possible. The content and design determine the breaking point of that grid, not the device sizes, so it's necessary to work in the medium of the final product. In the web, this means low-fidelity wireframing in code and browser. Different combinations and types of content and content displays will likely require different breakpoints and different grids, sometimes requiring only one grid for the whole range of displays, sometimes requiring many grids. The responsive layouts created for these content and design pairs can and should be reused even if the individual grids and breakpoints that make them up are not.

**Comment by kathrynmcelroy** [comment]
Design looks great!

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/grids.html

Page updated with new content

**Comment by Snugug** [comment]
@kathrynmcelroy Please update the copy [on the Wiki page](https://github.com/IBM-Watson/design-library/wiki/Grids) so we can preserve the markdown and structure.

**Comment by kathrynmcelroy** [comment]
@Snugug Didn't realize (until now) that I could edit someone else's wiki page. 

That being said, I've been giving edited text to the authors to decide if they want to use/keep any of my changes versus the original, and then they should be updating the wiki based on what they decide.

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1: Looks and Reads great!

**Comment by poofichu** [comment]
@Snugug I'm still working with her on a few things, then I'll update the wiki with the new content

**Comment by Snugug** [comment]
@poofichu @kathrynmcelroy The Wiki is a Git repository as well. Any changes you make get automatically tracked. If we want to revert to a previous version, it's the same as any other Git repo.

**Comment by poofichu** [comment]
![image](https://cloud.githubusercontent.com/assets/6757613/7025973/88b87902-dd0c-11e4-9280-e30cfa1d3fd9.png)

**Comment by bobbinrobyn** [comment]
:+1:

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
:+1: design done content done via #167
