### ISSUE TITLE
Responsive refinement for sub-nav

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#173]

**Comment by Lhuihui** [comment]
Hey, everyone! Add a breakpoint at 700px. 

Original:
![screen shot 2015-04-21 at 3 14 38 pm](https://cloud.githubusercontent.com/assets/2365989/7262158/11153318-e83d-11e4-8a15-4b7c922c5e6d.png)

Proposed:
![screen shot 2015-04-21 at 3 36 51 pm](https://cloud.githubusercontent.com/assets/2365989/7262162/1a6bddf4-e83d-11e4-8b2e-74acc7eea6e5.png)

The "Design Watson Experience" part break to two lines.
Maybe we can make the font smaller like this?
![screen shot 2015-04-21 at 3 44 34 pm](https://cloud.githubusercontent.com/assets/2365989/7262224/801f0f7c-e83d-11e4-9754-f36db23d6bd1.png)

**Comment by britanyponvelle** [comment]
I would like to avoid reducing the size because the hierarchy is not very clear in the second example. The size we chose was the next size up on the modular scale we are using for text. I think it is fine if "Design Watson Experiences" breaks to two lines. Thoughts?

Also, can we make sure that "Design Watson Experiences" aligns with the heading underneath it?

**Comment by poofichu** [comment]
@britanyponvelle Agreed with it going to two lines.  Totally cool with that.

**Comment by Lhuihui** [comment]
@britanyponvelle @poofichu Sure. We can stay with the original font-size and make it align right. But how about the sub-nav?

**Comment by britanyponvelle** [comment]
Is this still at 700px?

**Comment by Lhuihui** [comment]
Used to be 900px

**Comment by britanyponvelle** [comment]
How wide is the second column here?

**Comment by Lhuihui** [comment]
the main content part is around 450px

**Comment by britanyponvelle** [comment]
Ok great! When the main content gets smaller than 25em (around 400px) I think we should move the sub-nav to the top as a general rule. Anything below that gets too narrow and hard to read.

**Comment by britanyponvelle** [comment]
Tomorrow, can we try and see what the sub-nav looks like when under 700, at the top, and the grey box spans half the width instead of the whole width? This is another option for fighting the awkward space on the right...

![screen shot 2015-04-21 at 5 00 13 pm](https://cloud.githubusercontent.com/assets/9538528/7263537/ff2ba136-e847-11e4-9286-2b2c00f19d8d.png)

**Comment by Snugug** [comment]
How did you come up with these numbers? I find that when choosing breakpoints in the browser, I very very rarely see breakpoints come out to even `10px`s none the less even `50px`s. I can jump in and help out later today if you'd like, but I'd like to make sure we're choosing breakpoints in browser, per component, and not necessarily tie all components together.

**Comment by Lhuihui** [comment]
Sure. More than happy to sit down with you to figure this out.

**Comment by britanyponvelle** [comment]
Here is an update on sub nav:

Breakpoint at 660px:

![screen shot 2015-04-24 at 10 53 00 am](https://cloud.githubusercontent.com/assets/9538528/7323051/991e1a00-ea71-11e4-8b5b-7f59dfa0cda9.png)

Eva and I experimented with a few options: 

**Option 1:** Under 660px, 1/3 width of container

![screen shot 2015-04-23 at 2 50 58 pm](https://cloud.githubusercontent.com/assets/9538528/7323090/d42b6dd2-ea71-11e4-884d-6133bd09aedc.png)

**Option 2:** Under 660px, 1/2 width of container

![screen shot 2015-04-23 at 2 51 16 pm](https://cloud.githubusercontent.com/assets/9538528/7323104/e83d24c8-ea71-11e4-8373-0bf2ecf3dcc3.png)

**Option 3:** Under 660px, full width of container & centered

![screen shot 2015-04-24 at 10 44 47 am](https://cloud.githubusercontent.com/assets/9538528/7323199/82aae2ac-ea72-11e4-95db-d21064f0963d.png)


**Option 4:** Under 660px, full width of container (original)

![screen shot 2015-04-24 at 11 08 51 am](https://cloud.githubusercontent.com/assets/9538528/7323189/7100d4a8-ea72-11e4-8e5e-3fb7bcfd7ddc.png)

---

My thoughts are that making the width of the grey box does not get rid of the white space (which I do not personally have a problem with) so I think Option 4 is the best option. We could wrap the text around the nav on the right side-- but that makes the measure less than 350px and ~48 characters in the measure (which is something I think we should avoid because ideal measure is around 50 characters)

@IBM-Watson/design-acceleration thoughts?

**Comment by Snugug** [comment]
Did you try one where it gets split into multiple columns, or is that out?

**Comment by britanyponvelle** [comment]
@Snugug we were playing with that, but when there are multiple columns the links in the sub nav look as though they are grouped into either "Principles", "Guidelines" or "UI Patterns", whichever they are closest too

**Comment by Lhuihui** [comment]
@Snugug @britanyponvelle Here is a screenshot of two columns

![screen shot 2015-04-24 at 11 37 59 am](https://cloud.githubusercontent.com/assets/2365989/7323756/9aafd53e-ea76-11e4-99af-b8d9ef5eda53.png)

**Comment by britanyponvelle** [comment]
I think the second column throws off the hierarchy. Thoughts @IBM-Watson/design-acceleration ?

**Comment by bobbinrobyn** [comment]
Hmmm... it's not bad! I could get on board with this. Especially if you break up the categories so that the second column always starts with heading.

**Comment by britanyponvelle** [comment]
My only concern with this one is that users might think that the columns belong to the main nav links above it (although without user testing we can't be sure). But other than that, I agree that two columns looks better than having unnecessary space on the right :)

**Comment by ryanbrownhill** [comment]
Agreed - two columns looks better, but I worry that the usability as the selection doesn't go across the entire subnav anymore.

**Comment by joshkimmell** [comment]
Yeah... I think we're trying to solve a non-problem. Let's test the original subnav design and see what kind of feedback we get. Sound okay?

**Comment by britanyponvelle** [comment]
:+1:

**Comment by ryanbrownhill** [comment]
Ok decision is to stick to the original sub-nav for initial release then test. With that said, I :+1:

**Comment by Snugug** [comment]
:+1: 

Closing, as there is no need for refinement!
