### ISSUE TITLE
Design Footer

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#197]
Need footer to include:
Privacy Statement
Terms
Link to GitHub Repo
Contact Email link

**Comment by ryanbrownhill** [comment]
Extending this from #121 

@joshkimmell : 
![f1ea207a-edb4-11e4-9c70-ebdd3ec54b1b](https://cloud.githubusercontent.com/assets/9538395/7379363/0421aae2-edba-11e4-9c18-b8d8fe8f4657.jpg)
Here's the latest...
added rough footer
icons are 32x32

**Comment by ryanbrownhill** [comment]
I think that the footer could be skinnier. I am imagining something more like this:

![screen shot 2015-04-28 at 2 58 54 pm](https://cloud.githubusercontent.com/assets/9538395/7379178/8794627c-edb8-11e4-83a9-f460c4522d66.png)

**Comment by britanyponvelle** [comment]
I don't think the "Drop us a line" button is necessary. We don't use buttons anywhere else on the site to navigate to another page, so perhaps just  a link would be enough

**Comment by britanyponvelle** [comment]
(this way it wouldn't be so tall)

**Comment by joshkimmell** [comment]
![getting_started_v12-3](https://cloud.githubusercontent.com/assets/8161298/7380960/cbfc321c-edc4-11e4-9071-13902c637eea.jpg)
eh?

**Comment by joshkimmell** [comment]
![getting_started_v12-1](https://cloud.githubusercontent.com/assets/8161298/7380972/ed28cefa-edc4-11e4-92f3-efe2a2759726.jpg)

**Comment by ryanbrownhill** [comment]
@joshkimmell is the black link in the footer on purpose or is that a result of screen capturing?

**Comment by joshkimmell** [comment]
what are you talking about?

**Comment by joshkimmell** [comment]
Oh... "black" link. I was looking for a "back" link.

**Comment by ryanbrownhill** [comment]
black line* sorry...

**Comment by joshkimmell** [comment]
Oh... the bottom border is intended to act as a visual anchor.

wow... back link --> black line

**Comment by britanyponvelle** [comment]
The grey bar has the look of a footer which indicates the end of a page, so in my opinnion  I don't think the black line is necessary

**Comment by ryanbrownhill** [comment]
I agree with @britanyponvelle  - black line is no necessary. Since the bar is grey.

**Comment by bobbinrobyn** [comment]
I agree, no black line. Also just curious who that email is going mail to? We want to make sure we capture feedback and respond to it, so I would vote to only include that email link if there's someone responsible for keeping up with it.

**Comment by joshkimmell** [comment]
doesn't have to be email. We need a way for people to give us feedback. Could be GitHub issue queue. Whatever.

**Comment by britanyponvelle** [comment]
I like that idea! Linking to the contributor guidelines maybe?

**Comment by Snugug** [comment]
100% GitHub issue queue. Didn't know that was a question.

**Comment by ryanbrownhill** [comment]
:+1: Github Issue Queue.

**Comment by Snugug** [comment]
We should also have the version number in the footer

**Comment by Lhuihui** [comment]
It might be better to have another screen of footer with other page(i.e. grid page) to make sure the gray works

**Comment by joshkimmell** [comment]
Great feedback, guys!

**Comment by joshkimmell** [comment]
workin on it

**Comment by bobbinrobyn** [comment]
If it's not sending someone an email, I would hesitate to use the envelope icon. But that's great that we'll be directing people to the GitHub issue queue.

**Comment by Snugug** [comment]
Agreed with @bobbinrobyn. Here's the [NounProject Feedback icons](https://thenounproject.com/search/?q=feedback) for inspiration. Don't know if we have anything similar in our icons already.

**Comment by joshkimmell** [comment]
I have a mockup using GitHub's issue queue icon

**Comment by joshkimmell** [comment]
shortly

**Comment by joshkimmell** [comment]
@Snugug: remind me what the version number will be. Version 1.0.0?

**Comment by Snugug** [comment]
I'm OK with that, but do you think that'll be a widely-known enough icon for general use? On GitHub they use [progressive reduction](http://layervault.tumblr.com/post/42361566927/progressive-reduction) to get a user to a place where they just recognize the icon.

It will be `v1.0.0` when we launch, but we may also have betas available (like we do now) so it needs to be flexible to not just 6 characters

**Comment by joshkimmell** [comment]
![getting_started_v13-1](https://cloud.githubusercontent.com/assets/8161298/7417186/f4ce266c-ef29-11e4-9fcf-73a0a86f5bba.jpg)

**Comment by joshkimmell** [comment]
![getting_started_v13-2](https://cloud.githubusercontent.com/assets/8161298/7417266/933dc8ac-ef2a-11e4-91bc-66139f4f4a18.jpg)

**Comment by britanyponvelle** [comment]
Hmm, separating the Github links form the other links into seperate bars doesn't seem necessary. I think it would make more sense to have them all in the same group.

**Comment by ryanbrownhill** [comment]
Agreed - Also I don't think the teal works for the github buttons (maybe teal on hover) but currently the teal makes the buttons too much of a focus for a hooter.

**Comment by britanyponvelle** [comment]
Also, I think the grey bar was nicer here. The dark grey bar seems to outweigh the content above it

**Comment by britanyponvelle** [comment]
I think the light grey bar for the footer works the best. The dark grey outweighs the content above it.

**Comment by poofichu** [comment]
Footer on Animation page:
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/animation.html

Footer on Homepage:
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

Centering to me is OK, because we center the nav at the top on smaller screens.  It almost could use the logo as some sort of graphical interest... I'll play with that tomorrow.

**Comment by britanyponvelle** [comment]
I agree, centered footer content for smaller browsers makes sense since we center the top nav.  

For the wider screens, flush left on one side and flush right on the other is awkward. I think aligning the content to the column above it would feel more balanced.

![screen shot 2015-05-01 at 9 25 58 am](https://cloud.githubusercontent.com/assets/9538528/7431449/58d0fae4-efe4-11e4-994e-a90a264002c9.png)

The grey bar with dark grey and orange text/ icons becomes heavy at the bottom of the page, especially if there is no scroll (like here). I think reducing the text size would make this better. We could use our caption size here! It's pretty common to have smaller text in the footer, since it's less critical than the main content on the page.

![screen shot 2015-05-01 at 9 14 40 am](https://cloud.githubusercontent.com/assets/9538528/7431516/d4c303f4-efe4-11e4-9918-622ac1a3d74b.png)

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

Made the font the next smaller size for both smaller and larger screens.

Also, increased the padding top and bottom.  @britanyponvelle approved.

**Comment by Snugug** [comment]
OOC, why is the GitHub logo so prominent? If we've got `Submit an Issue` and `View the Code`, do we need a giant GitHub logo there too?

Maybe move the Version information to where the GitHub logo is instead?

What are everyone's thoughts on `View Source` instead of `View the Code`. Where does Privacy and Terms of Use link to? It may be more beneficial to call out the specific licenses (most likely CC-BY for guidelines, Apache-2.0 for code) instead of Terms of Use. Something like:

```
Documentation licensed under the CC-BY license
Code licensed under the Apache 2.0 license
```

**Comment by bobbinrobyn** [comment]
I'm also wondering what those Privacy & Terms of Use pages will be...? @Snugug's solution sounds like a good one!

And although I don't think the GitHub logo is gigantic :stuck_out_tongue:, I could see us removing it and changing the text to read "Submit an Issue on GitHub." Maybe that way we wouldn't need the logo, but users would still know where that click will take them.

**Comment by joshkimmell** [comment]
![footer_v1-1](https://cloud.githubusercontent.com/assets/8161298/7459890/e0982f9c-f264-11e4-9b42-32ec1bb222d2.jpg)

feel free to comment on color, but focus on footer content.

**Comment by Snugug** [comment]
Well, don't like the color.

CC-BY and Apache-2.0 should link to their licenses (potentially even in our repo; right now we only have Apache). Version should link to [GitHub Version](https://github.com/IBM-Watson/design-library/releases/tag/v1.0.0-beta.3).

I prefer Version Number/Issue/Source grouped and Licenses grouped as opposed to Licenses being grouped with Version. I prefer this because, per our [Contributing Guidelines](https://github.com/IBM-Watson/design-library/blob/develop/CONTRIBUTING.md), we want users to submit issues with the version number and decoupling the two makes it harder to find/less likely to be seen if that's what you're looking to do. I also think it generally gets lost amongst the license text.

**Comment by joshkimmell** [comment]
![getting_started_v14-3](https://cloud.githubusercontent.com/assets/8161298/7463477/77e3ef70-f27f-11e4-97a9-53eb1c53a2bc.jpg)

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

We kept the light grey.  It seemed to work better with what content we had going on above it.
Thoughts?

**Comment by joshkimmell** [comment]
remove underline from icons

**Comment by Snugug** [comment]
I still prefer the dark header to the light one :\

**Comment by poofichu** [comment]
@Snugug We're going to test this out with a few more people around studio.  We had another designer from Analytics take a look at the new design (she's been following the progress of our prototype) and made a point to tell us she liked the lighter banner better.

@joshkimmell they're not underlined.  Refresh please!

**Comment by poofichu** [comment]
http://pages.design.ibm.com/tremblay-us/ibm-watson-design-library/master/dist/index.html

Can I get a :+1: ??

**Comment by ryanbrownhill** [comment]
I would like it a little skinner maybe 1.5em? vs 3em.

**Comment by joshkimmell** [comment]
![image](https://cloud.githubusercontent.com/assets/8161298/7483636/1910cdac-f346-11e4-8465-66e1ee1996e6.png)
 screenshot

**Comment by ryanbrownhill** [comment]
:+1:

**Comment by kathrynmcelroy** [comment]
:+1:

**Comment by britanyponvelle** [comment]
:+1:

**Comment by joshkimmell** [comment]
:+1:

**Comment by Snugug** [comment]
Launched!
