### ISSUE TITLE
Update assets and examples on Logo page

### ISSUE THREAD

**Issue by britanyponvelle** [IBM-Watson/design-library#204]
Updates needed:

- [x] Add logo with thought rays
- [x]  Remove logotype without thought rays
- [x] update examples
- [x] adjust guidelines accordingly 
- [x] Update all wordmark assets to include the trademark
- [x] Update markdown file

**Comment by britanyponvelle** [comment]
@joshkimmell did I miss anything?

**Comment by joshkimmell** [comment]
Add content around "Powered by"

**Comment by britanyponvelle** [comment]
@joshkimmell The "Powered by" asset has a trademark associated with it, but the wordmark we use does not. Is the trademark still relevant?

![screen shot 2015-04-30 at 11 35 46 am](https://cloud.githubusercontent.com/assets/9538528/7417655/1c78941a-ef2d-11e4-8198-925275b08fad.png)

**Comment by joshkimmell** [comment]
Good catch. I believe it all needs trademarks now.

**Comment by britanyponvelle** [comment]
Hmm so would that mean the trademark needs to be in our header as well? I don't see a minimum size for that in the PDF, so I would think it would but I'm not sure.

**Comment by britanyponvelle** [comment]
(header for the Design Guide)

**Comment by joshkimmell** [comment]
Good point. I'm not sure that pertains to product names. I'll find out.

**Comment by joshkimmell** [comment]
- Wordmark
- Product name
- Powered by
- Ecosystem Partner

**Comment by britanyponvelle** [comment]
So just to be clear and to get everyone on the same page, the logotype is out completely, 

![screen shot 2015-04-30 at 3 08 26 pm](https://cloud.githubusercontent.com/assets/9538528/7421527/c9b90a0c-ef4a-11e4-9fb2-3e008f162d7d.png)

but the use of the logo *alone* is allowed. 

![screen shot 2015-04-30 at 3 09 16 pm](https://cloud.githubusercontent.com/assets/9538528/7421539/e296fe76-ef4a-11e4-8def-1f18290b4af1.png)

@joshkimmell correct?

**Comment by joshkimmell** [comment]
yup

**Comment by joshkimmell** [comment]
:globe_with_meridians:

**Comment by bobbinrobyn** [comment]
Here's the copy we can use for Ecosystem partner mark. *However* in the Partner Guidelines, I think the Ecosystem partner mark is specifically for use in print & digital communication artifacts (banners, emails, ads, etc.) I don't know that an Ecosystem partner would ever use it in a software product or application.

**So in my opinion, we shouldn't include this.**

*Ecosystem Partner Mark*
The IBM Watson wordmark should be used in communications that reference the overall IBM Watson brand, whereas the Ecosystem Partner mark should be used in communications that reference the relationship between an Ecosystem partner and IBM Watson. The Ecosystem Partner mark should always be positioned so that it is clear visible in communications, yet subordinate to the Ecosystem partner’s brand.

*Specifications*
[Keep the area around the Ecosystem Partner mark separated from other visual elements by a distance approximately equal to the height of the type in the mark. This distance is considered the minimum uninterrupted space surrounding the mark. A minimum size of 100px wide by 25px high should be followed to ensure legibility.]

**Comment by bobbinrobyn** [comment]
That being said, an Ecosystem parter WILL use the "Powered by IBM Watson" mark. So here's the copy for that.

*Powered by IBM Watson™ Wordmark*
For an app that has been developed by an Ecosystem partner using IBM Watson, and has either launched for commercial release or is in late-stage development, the recommended mark is "Powered by IBM Watson™". Use the wordmark within applications on screens specific to IBM Watson capabilities and on application-specific websites or communications that refer to IBM Watson technology.

*Specifications*
[Keep the area around the "Powered by IBM Watson™" wordmark separated from other visual elements by a distance approximately equal to the height of the IBM Watson word mark. A minimum size of 57px wide by 8px high should be followed to ensure legibility of the mark.]

**Comment by britanyponvelle** [comment]
Here are the updated sections. Thoughts?

![screen shot 2015-05-04 at 9 48 11 pm](https://cloud.githubusercontent.com/assets/9538528/7466384/6d850da2-f2a7-11e4-8157-5b8ee63b8e19.png)

![screen shot 2015-05-04 at 9 48 31 pm](https://cloud.githubusercontent.com/assets/9538528/7466385/716725b8-f2a7-11e4-8a92-40de075e8857.png)

![screen shot 2015-05-04 at 9 48 47 pm](https://cloud.githubusercontent.com/assets/9538528/7466386/740a068c-f2a7-11e4-8f59-e8325899cbde.png)


http://pages.design.ibm.com/blponvel/ibm-watson-design-library/master/dist/wordmark-logotype.html

**Comment by bobbinrobyn** [comment]
These look great! Thanks for updating all of those assets.

Two thoughts:
1. The titles feel redundant where it says Powered by IBM Watson Wordmark and then Ecosystem Partner Wordmark.  Do we need the first title?
2. Do we need a guideline about not combining the wordmark and logo? Is that something we're wanting people to explicitly avoid?

**Comment by ryanbrownhill** [comment]
@britanyponvelle Agree with @bobbinrobyn I think we should remove one of the titles. I vote keeping the first title actually. 

I think we should have a guideline around not combining the wordmark and logo.

**Comment by britanyponvelle** [comment]
:+1:
