### ISSUE TITLE
Correctly rendered patterns

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#294]
Some of these patterns are rendering weird...

- [x] [Buttons](http://watsondesign.guide/ui-patterns/patterns/base/button/) - these are tiny, and they don't really look like our buttons
- [x] [Input-Color](http://watsondesign.guide/ui-patterns/patterns/base/input--color/) - there should probably be some kind of indication that clicking will bring up the color picker
- [x] [Input-Image](http://watsondesign.guide/ui-patterns/patterns/base/input--image/) - why is there a button that says submit? This isn't at all what I would expect for an image input.
- [x] [Input-Month](http://watsondesign.guide/ui-patterns/patterns/base/input--month/) - I expected this to be a dropdown with a list of months, as opposed to a calendar. Anybody else?
- [ ] [Input-Range](http://watsondesign.guide/ui-patterns/patterns/base/input--range/) - really just the disabled state. It's still clickable?
- [x] [Input-Week](http://watsondesign.guide/ui-patterns/patterns/base/input--week/) - those controls are tiny! And weirdly arranged...
- [x] [Loading Indicator](http://watsondesign.guide/ui-patterns/patterns/components/loading-indicator/) - rendered pattern doesn't show up (#331)
- [x] border around inputs should get thicker on focus
- [ ] border around search input gets TOO thick on focus

**Comment by Snugug** [comment]
Month and Week are native browser controls, we have no way of styling/changing them :\

**Comment by Snugug** [comment]
Couple of thoughts on these:

* Buttons are styled as we had buttons ~3 months ago when they went in. If our button style has changed, we should update these
* The Image input type is [a graphical Submit button](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input). That pattern needs to be updated to actually represent that, but it _should_ be a submit button
* Color, Month, and Week are native form controls so we can't do much to change their appearance within base elements. We can enhance them once we get around to writing components (and we should), but for the time being we can't do much with them. Try them out in Firefox and Safari and you'll see what happens if they aren't natively supported.

Loading indicator needs to get fixed. I could have sworn I had this working; clearly not.

**Comment by Snugug** [comment]
For the Image input type, if we don't want people using it, we can talk about simply removing it

**Comment by Snugug** [comment]
Loading Indicator fix blocked on https://github.com/IBM-Watson/design-library/pull/324

**Comment by bobbinrobyn** [comment]
@snugug: http://localhost:3000/ui-patterns/patterns/base/input--color/

square 3em x 3em

**Comment by bobbinrobyn** [comment]
Work on this super classy gradient: http://localhost:3000/ui-patterns/patterns/base/input--file/

**Comment by bobbinrobyn** [comment]
I think this is an issue for you, @Snugug:
Input-Range - really just the disabled state. It's still clickable?

**Comment by bobbinrobyn** [comment]
[This is what we want](http://localhost:3000/ui-patterns/patterns/base/input--search/) to happen on focus – a change in color *and* border-width. It's only happening on this one input, though. We'd like it to happen on *all* of the inputs on focus.

![image](https://cloud.githubusercontent.com/assets/9341504/7734756/e28be302-fefd-11e4-9277-33a8401c9a3a.png)

**Comment by bobbinrobyn** [comment]
Actually something is wrong with just the search input :disappointed: 

I fixed the border thickness issue for all the other inputs, but Search is now showing up extra thick on focus. I can't tell what's making that happen.
