### ISSUE TITLE
Animated examples should auto-start

### ISSUE THREAD

**Issue by joshkimmell** [IBM-Watson/design-library#326]

**Comment by Snugug** [comment]
I thought we had decided not to have videos autoplay

**Comment by joshkimmell** [comment]
I'm going by what was in the prototype. I strongly feel that the examples should auto-start

**Comment by Snugug** [comment]
The prototype doesn't 100% reflect all decisions made.

@IBM-Watson/design-acceleration do we want videos to auto-play?

**Comment by joshkimmell** [comment]
I agree, but think about it from a user's perspective. Would a user who is reading the guidelines click 'play' on an example?

**Comment by Snugug** [comment]
It's a video? I think it's a safe assumption that if a user sees a play button that they'd understand that clicking play will start a video.

**Comment by joshkimmell** [comment]
I just user tested this in the coffee shop with 3 people. They all agree an example should auto-play. It's not optional, it's necessary for the user to understand the concept.

**Comment by joshkimmell** [comment]
If we're not all in agreement, we should test this with our "real" users.

**Comment by Snugug** [comment]
I would ask if those people were representative of our primary users, but yes, real testing with controlled questions targeting our primary users is always best.

**Comment by kathrynmcelroy** [comment]
The videos should start automatically bc they are essential to understanding the surrounding information. The user can still pause the video, but it should be running with the controls hidden until mouse over. If a user is skimming, which is likely to happen as seen from our research, they do not take the time to push play, so having them play automatically will help all our users experience and understand through the videos.

It's especially necessary for the comparisons so that they are running at the same time and you can see the differences.

**Comment by poofichu** [comment]
Agreed with @kathrynmcelroy.  Also, what about the custom styled video controls?  Are we doing those?

**Comment by Snugug** [comment]
All videos, or just some videos?

**Comment by poofichu** [comment]
I would say all.  Consistency.

**Comment by kathrynmcelroy** [comment]
All videos. If we do it in one place, we should do it in all for the system.

**Comment by bobbinrobyn** [comment]
My one hesitation would be any instances with more than 2 videos visible at one time. I think that might be overwhelming. But otherwise, I think it makes sense to have videos autoplay... it seems like that would reduce friction for the user.
