### ISSUE TITLE
Feature/Loading Indicator

### ISSUE THREAD

**Issue by Snugug** [IBM-Watson/design-library#65]
Loading indicator component when we don't know percent done (should use #63 when we do)

**Comment by ryanbrownhill** [comment]
![watson_black_150px](https://cloud.githubusercontent.com/assets/9538395/6446128/66a61d2e-c0ce-11e4-836c-b8236317161d.gif)
@Snugug Shall we just convert this into a svg animation component or shall I design a new one?

**Comment by Snugug** [comment]
@ryanbrownhill Whichever you'd prefer.

Requirements for this:

- [ ] Single SVG
- [ ] Accessible base that gets across loading if SVGs are not available
- [ ] Less than 14kb minimized
- [ ] Customizable (especially color, but maybe speed too)

We can discuss if it's something to be applied as an inline SVG, an image tag, or as CSS once you've decided which direction to go.

If you decided to convert this to SVG, I'd like to see a couple of extra frames with the outer circle complete; right now it looks like the circle never finishes because it starts to fold in on itself so quickly.

**Comment by ryanbrownhill** [comment]
@Snugug I will start working on converting the above to an svg animation. 
We can discuss our accessibility options - I am under the assumption that we can use meta-tags within the svg?

**Comment by Snugug** [comment]
Accessibility will depend on how we choose to implement the loader. There are a few resources you can look at though:

* http://www.sitepoint.com/tips-accessible-svg/
* http://www.paciellogroup.com/blog/2013/12/using-aria-enhance-svg-accessibility/
* http://www.w3.org/TR/SVG-access/

**Comment by ryanbrownhill** [comment]
- [] Setup SVG for animation

**Comment by ryanbrownhill** [comment]
- [ ] Export New SVG for Watson Logo (Current one isn't suitable as the strokes are outlined and which doesn't allow for animate along path.
- [ ] Setup SVG for Animation (Organizing the SVG file so ready for animation)
- [ ] Animate Watson Logo SVG 
- [ ] Add Scaling Animation to logo
- [ ] Add additional exterior stroke & circle animation
- [ ] Research CSS or SVG Masking for for the resolve

**Comment by ryanbrownhill** [comment]
Current Status of the SVG Animation:
![watson-3](https://cloud.githubusercontent.com/assets/9538395/6511432/8011691a-c332-11e4-9a13-aeb1c9dafa31.gif)

What I am currently working on:
- Still figuring out how to move the does to resolve on different locations of the stroke. 
- Working on the getting the easing & timing right.
- Adding CSS or SVG masking

**Comment by Snugug** [comment]
Looking good! I like! Couple questions:

* Is there going to be an out animation or just an in one? The original one you had posted goes in and out, just curious if you plan on the same thing for this.
* Have you thought about the [implementation style](https://github.com/IBM-Watson/patterns/issues/65#issuecomment-76761728) and other things in that comment?

**Comment by ryanbrownhill** [comment]
@Snugug 
- Yes the animate out will be a mask off of the SVG.
- I have I am thinking something like this for the implementation style:  `<object type="image/svg+xml" data="img/WatsonAvatar.svg"><!--fallback--></object>` with the maybe a fallback gif within the object?
- For accessibility I will be adding proper `<title>` `<desc>` & `roles=""`

**Comment by Snugug** [comment]
Cool. Sounds good! I'm excited.

**Comment by ryanbrownhill** [comment]
@Snugug - I added you to the git lab project so you can see the code as I work. Right now I am writing the CSS inside the SVG file (which is only the Scale right now). I am doing this way because I figured we don't want to add an CSS file dependence to the SVG animation. Is this how I should be doing it?

**Comment by Snugug** [comment]
That should be good.

**Comment by ryanbrownhill** [comment]
![watson-4](https://cloud.githubusercontent.com/assets/9538395/6516999/77331c06-c35c-11e4-80df-e889f1e0255f.gif)
Update - Refining Timing. 
Going to research the masking tomorrow.

**Comment by ryanbrownhill** [comment]
![watson-5](https://cloud.githubusercontent.com/assets/9538395/6535817/77d8210e-c40d-11e4-96fb-343093a94d38.gif)
- Got Masking Working!! :+1: :tada: 
- Need to work on cross browser issues for animating `stroke-dashoffset` (Mozilla error)

**Comment by Snugug** [comment]
Awesome! Looks great!

Now I know this is going to sound like a weird question, but have you tested in IE, and if so, what version of IE? Is there a list of some of the advanced SVG features you're using so we know what we need to test for?

**Comment by ryanbrownhill** [comment]
@Snugug haven't tested in an IE - do you know how to do that without access to a PC? Also the SVG features we are using are:

- `<AnimateMotion>`
- `<Animate>`
- `stroke-dashoffset`
-  `stroke-dasharray`

The - `stroke-dashoffset` & `stroke-dasharray` are causing problems in moz. The problem is not that the `stroke-dashoffset` &  `stroke-dasharray` don't work. It is that they don't animate.
Here a blog post some one did on the subject [Animating line drawing](http://jakearchibald.com/2013/animated-line-drawing-svg/)

As far as IE - SMIL doesn't work in IE. So would it be suitable to use a GIF fallback or should we use something like [Snap.svg](snapsvg.io) - I know snap would add an additional dependency we don't want. Do you know of any alternatives? All I know of is [GSAP](http://greensock.com/gsap) and it seems that it would be even heavier than Snap.svg

**Comment by Snugug** [comment]
Snap is 73KB minified; that's too big for me, much happier to do a GIF fallback provided that we can test for those features.

**Comment by Snugug** [comment]
You can test in IE with either http://www.browserstack.com/ or [Modern.ie](https://www.modern.ie/en-us) virtual machines

**Comment by ryanbrownhill** [comment]
@Snugug What do you mean but testing for those features? - How would I go about checking if we can do that?

**Comment by Snugug** [comment]
Take a look at [Modernizr](http://modernizr.com/). We're going to need to devise Modernizr style tests for the features we want to use so that we can enhance from our basic loading feature (which will be our `gif`) to the SVG.

**Comment by ryanbrownhill** [comment]
Update: 
Refactored my code and setup a new gulp file so that I would have SASS styling.... then I realized that all the CSS has to be inline inside the SVG... So I am just using gulp to auto-prefix any new CSS that is written then paste that inline.

Been researching fallbacks & reading up on Modernizr. 

My findings:
Tried `<object>` which has its own html fallback mechanism but doesn't seem to work. From what I understand the fallback will only trigger if SVG's as a whole is not supported not just the Animation portion of SVG's.

Will probably going this route with Modernizr trigger:
![screen shot 2015-03-10 at 2 37 14 pm](https://cloud.githubusercontent.com/assets/9538395/6583605/2e1c5070-c733-11e4-84ca-5a47c4b98892.png)
An alternative would be using a `background-image` for both the GIF and SVG in CSS with a Modernizr trigger. 
![screen shot 2015-03-10 at 2 40 18 pm](https://cloud.githubusercontent.com/assets/9538395/6583643/6c3a8228-c733-11e4-8183-e8b42bb5e13b.png)

Continuing to look into Modernizr in more detail. 
I am going to look to see if we can test compatibility for SVG Animation with Modernizr if not we could do a browser type trigger for the SVG enhancement?

Resources:
[SVG Fallbacks](https://css-tricks.com/svg-fallbacks/)

**Comment by Snugug** [comment]
So here's the tricky bit: we aren't going to do browser sniffing because it's not a sustainable practice and it's often (and easily) tricked. Is there a way to to use [`@supports`](http://caniuse.com/#search=supports) to check for CSS animations? Provide a basic animation if advanced CSS animations aren't available, more advanced ones if they are. Layered levels of animation based on levels of support.

**Comment by ryanbrownhill** [comment]
@Snugug Hmmm okeys. I will look into `@supports`. Another tricky part is that there is two types of animation: 
1. The SVG animations with `<animate>` & `<animateMotion>`
2. CSS `@keyframes`

**Comment by Snugug** [comment]
Yup, this'll be a challenge. Maybe @una can help

**Comment by ryanbrownhill** [comment]
Figured out the looping within SMIL I have created two versions. 

1. Animates and loops the entire animation (Like the original gif above). 
![watson-6](https://cloud.githubusercontent.com/assets/9538395/6629029/dc43e19e-c8d8-11e4-9661-a0ec8e9a266e.gif)

2. Animates the graphic on and loops a progress circle
![watson-7](https://cloud.githubusercontent.com/assets/9538395/6629030/dc4534b8-c8d8-11e4-9aee-990aff0d2230.gif)

We could figure out a trigger for the animation to resolve or build some kind of progress feature to the exterior ring that could read the actual progress. Also the second option could be used as the loading bar as well.

**Comment by Snugug** [comment]
To me the key difference between a loading indicator and a progress bar is that a progress bar shows % complete whereas a loading indicator is more like a waiting indicator where we don't know how much we have to wait.

I like both of them though. I guess the question is how much do we want going on during the waiting? Looping the whole thing will make it appear that much more is happening (cause there's more motion) but it's also more noisy? Maybe? I don't know. Anyone else have thoughts?

**Comment by ryanbrownhill** [comment]
Agreed - I think the second one might be a little bit too noisy. I think the second one would be better suited. 

I can continue with the second animation and figuring out how to make this more production ready but I believe it will take me quite sometime. I am happy to continue do it but I will need someone that has more front end expertise to help me finalize this. My main front end challenge is the creating a proper fallback or enhancement as mentioned above.

**Comment by Snugug** [comment]
Modernizer v3 has a feature detect for SMIL
http://v3.modernizr.com/download/

We should also connect with Marketing on this, apparently using the logo to indicate loading is against the band guidelines for the avatar

**Comment by joshkimmell** [comment]
We should connect, though technically it isn't the logo. There are no lashes.

**Comment by Snugug** [comment]
logo/avatar I'm sure they don't make a distinction. But yes, we should connect.

**Comment by bradbecker** [comment]
I thought this was for thinking and processing. 

-b

**Comment by Snugug** [comment]
@ryanbrownhill How's the progress on this?

**Comment by ryanbrownhill** [comment]
@Snugug @una added a javascript trigger so that the animation ends on click ( or any other javascript event ). I believe all that needs to be done is making it a gif and creating the fallback - I can chat with you or @eva about it?

Here is the link to the current SMIL animation with the Javascript trigger.
https://git.design.ibm.com/rgbrownh/watson-avatar-loader/blob/master/img/WatsonAvatar-exterior.svg

**Comment by Snugug** [comment]
Awesome. Have you done any cross-browser testing yet?

**Comment by Snugug** [comment]
Also, you shouldn't bind to `onclick`, you should add an event listener and listen for click.

**Comment by ryanbrownhill** [comment]
@Snugug webkit browsers seem to be good. 
Firefox - clipping path out of place and strokes don't draw on.

**Comment by ryanbrownhill** [comment]
Added modernizr fallback, if SMIL is not supported then the GIF is shown.
https://git.design.ibm.com/rgbrownh/watson-avatar-loader/tree/master

Still having issues with Firefox not supporting `stroke-dasharray` & `stroke-offset` which is a subset of SMIL.

**Comment by ryanbrownhill** [comment]
Loading indicator is up and running with fallbacks. @Snugug Let me know if there is a better way to implement the fallbacks.

Here is the codebase for the SVG:
https://git.design.ibm.com/rgbrownh/watson-avatar-loader/tree/master

**Comment by ryanbrownhill** [comment]
@Snugug This is ready to become a Pull Request. Where shall I put it?

design-library/patterns/components/loading-indicator

**Comment by Snugug** [comment]
Partner with @britanyponvelle, follow the [Contributing Guidelines](https://github.com/IBM-Watson/design-library/blob/develop/CONTRIBUTING.md), and build a component!

Yah, that's the place to put it
